### ISSUE TITLE
No issui just an question

### ISSUE THREAD

**Issue by Michaelj15** [L2KPerma/FS22_RealDashboard#4]
Hello, 

Everything works fine and i love this dashboard, great job!
I have an question about the settings and options.
When i changing the values from pound to kg the numbers on the dashboard changed perfect. But after the digital numbers, the gross lb texture don't change. Is this correct? Or do i have something wrong in the mod?
Also on the mod preview photo, you have a dashboard with a gps display. Is this also editable with the mod, or is this display from the original tractor?
Is it also possible to add two dashboards in the same tractor? If yes, how do i edit the xml/ i3d to make it work?

Thanks for your work!

**Comment by L2KPerma** [comment]
Only the numbers are affected via the script, the units on the screen are a part of the texture for the screen itself and thus can only be changed if you edit the image.

As for the gps map that’s just a static screen in KarlFarms steigers. 

For two dashboards, theoretically you should be able to have two displays however, they would all show the same values with the way it is written.

**Comment by Michaelj15** [comment]
Okay, thank you!

Yes, I tested it and they have the same values. I was thinking for a screen like bulk and another for liquid. But no problem, it will be fine.
________________________________
